apiVersion: v1
kind: Secret
metadata:
  name: rem-secret
  namespace: rail-event-monitor
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  JWT_SECRET: change-me-change-me-change-me-change-me
